<?php
/**
 * SmsApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CELLVOZ Cloud Services API
 *
 * Cellvoz API SMS permite a nuestros clientes enviar de forma segura y eficiente mensajes de texto. Hemos mejorado la seguridad de consumo en nuestra nueva versión y la utilización de JWT para la autenticación y el uso de un API Key que se puede obtener mediante el backoffice y hemos agregado la funcionalidad de agregar la IP 0.0.0.0 para que puedas consumirla desde un servidor sin una ip fija.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: contacto@cellvoz.com.co
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * SmsApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SmsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation sms
     *
     * Enviar mensajes de texto sencillos, para el envio se debe enviar el JWT Token y el API Key
     *
     * @param  \Swagger\Client\Model\SMSRequest $body Envio de un mensaje de texto para celulares, el formato del numero de celular debe ser codigopais+numero, Ejemplo  Telefono en Colombia 573113455666, la longitud del texto a enviar no debe superar los 140 caracteres. (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\SMSResponse
     */
    public function sms($body)
    {
        list($response) = $this->smsWithHttpInfo($body);
        return $response;
    }

    /**
     * Operation smsWithHttpInfo
     *
     * Enviar mensajes de texto sencillos, para el envio se debe enviar el JWT Token y el API Key
     *
     * @param  \Swagger\Client\Model\SMSRequest $body Envio de un mensaje de texto para celulares, el formato del numero de celular debe ser codigopais+numero, Ejemplo  Telefono en Colombia 573113455666, la longitud del texto a enviar no debe superar los 140 caracteres. (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\SMSResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function smsWithHttpInfo($body)
    {
        $returnType = '\Swagger\Client\Model\SMSResponse';
        $request = $this->smsRequest($body);

        try {
            $options = $this->createHttpClientOption();
            //var_dump($options);
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\SMSResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ErrorResponseApi',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ErrorResponseApi',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ErrorResponseApi',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation smsAsync
     *
     * Enviar mensajes de texto sencillos, para el envio se debe enviar el JWT Token y el API Key
     *
     * @param  \Swagger\Client\Model\SMSRequest $body Envio de un mensaje de texto para celulares, el formato del numero de celular debe ser codigopais+numero, Ejemplo  Telefono en Colombia 573113455666, la longitud del texto a enviar no debe superar los 140 caracteres. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function smsAsync($body)
    {
        return $this->smsAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation smsAsyncWithHttpInfo
     *
     * Enviar mensajes de texto sencillos, para el envio se debe enviar el JWT Token y el API Key
     *
     * @param  \Swagger\Client\Model\SMSRequest $body Envio de un mensaje de texto para celulares, el formato del numero de celular debe ser codigopais+numero, Ejemplo  Telefono en Colombia 573113455666, la longitud del texto a enviar no debe superar los 140 caracteres. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function smsAsyncWithHttpInfo($body)
    {
        $returnType = '\Swagger\Client\Model\SMSResponse';
        $request = $this->smsRequest($body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sms'
     *
     * @param  \Swagger\Client\Model\SMSRequest $body Envio de un mensaje de texto para celulares, el formato del numero de celular debe ser codigopais+numero, Ejemplo  Telefono en Colombia 573113455666, la longitud del texto a enviar no debe superar los 140 caracteres. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function smsRequest($body)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling sms'
            );
        }
        //echo "token<br>";
//$this->config->setAccessToken("eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnZXJlbmNpYUB2ZXN0ZWwuY29tLmNvIiwidXNlciI6eyJuYW1lcyI6bnVsbCwiYWNjb3VudCI6bnVsbCwiaWR2Ijo2OTUzLCJpZHMiOjcwNjgsInRpcG9DbGllbnRlIjozMiwic2FsZG8iOjg3NzI5LCJjdWVudGEiOiIwMDQ4NjgwMDQzMCIsImVtcHJlc2EiOiJWRVNHQSBURUxFQ09NVU5JQ0FDSU9ORVMgUyBBIFMiLCJub21icmUiOiJWRVNHQSBURUxFQ09NVU5JQ0FDSU9ORVMgUyBBIFMiLCJyYXpvblNvY2lhbCI6IlZFU0dBIFRFTEVDT01VTklDQUNJT05FUyBTIEEgUyIsInRpcG9QYWdvIjoiUHJlcGFnbyIsImNpdWRhZCI6ImJvZ290YSIsImRpcmVjY2lvbiI6ImNhbGxlIDk0YSAxMy00MiIsImRvY3VtZW50byI6Ijg0NDAwNDk3OSIsImVtYWlsIjoiZ2VyZW5jaWFAdmVzdGVsLmNvbS5jbyIsInRlbGVmb25vIjoiMzEwNjA5NTY3NSIsImNvcnRlIjoiMTk4OC0wMS0wMSIsInRpcG9TdWJ1c3VhcmlvIjpudWxsLCJjbGF2ZSI6bnVsbH0sImlhdCI6MTYyMTg5MjA3OSwiZXhwIjoxNjIxOTc4NDc5fQ.PLKj3_aYp02YyRhko3PNdii0ab8sf5nAXhuDn_KkN-g");//el api key
//$this->config->setApiKey("0","a163f063dc8605d0faaa0d50ff43a9254034020b");
        //$this->config->setUsername("00486800430");
        //$this->config->setPassword("Admin2019");
        $resourcePath = '/sms/single';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }
        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            $headers['api-key'] = '8529863e6706e0659cb610dfaded9c36db43e989';
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
