<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbce16ea4bea1765c99273c010a3e036f
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'SMTPValidateEmail\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'SMTPValidateEmail\\' => 
        array (
            0 => __DIR__ . '/..' . '/zytzagoo/smtp-validate-email/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbce16ea4bea1765c99273c010a3e036f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbce16ea4bea1765c99273c010a3e036f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitbce16ea4bea1765c99273c010a3e036f::$classMap;

        }, null, ClassLoader::class);
    }
}
