<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'SMTPValidateEmail\\' => array($vendorDir . '/zytzagoo/smtp-validate-email/src'),
);
