<?php
/**
 * AuthApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CELLVOZ Cloud Services API
 *
 * Cellvoz API SMS permite a nuestros clientes enviar de forma segura y eficiente mensajes de texto. Hemos mejorado la seguridad de consumo en nuestra nueva versión y la utilización de JWT para la autenticación y el uso de un API Key que se puede obtener mediante el backoffice y hemos agregado la funcionalidad de agregar la IP 0.0.0.0 para que puedas consumirla desde un servidor sin una ip fija.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: contacto@cellvoz.com.co
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * AuthApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AuthApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for login
     *
     * Obtener Token de autorización.
     *
     */
    public function testLogin()
    {
    }
}
