name: Tests

on: [push]

jobs:

  tests:
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }} tests

    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1']

    steps:
      - uses: actions/checkout@v3
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          coverage: "none"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: make install
      - run: make test
